### ISSUE TITLE
Potential name clash on PyPI

### ISSUE THREAD

**Issue by hanslovsky** [scijava/jrun#19]
https://pypi.org/project/jrun/
I do not know if we need to care at all.

**Comment by ctrueden** [comment]
We could upload to PyPI as `javarun`, and/or rename the Python module to `javarun`.

If we publish to PyPI as `javarun`, but the module is still named `jrun`, does that cause a problem? E.g.: what if someone wants to have both `javarun` and `jrun` installed at the same time? That would be problematic, no? I guess only one of them would take precedence for `import jrun` statements?

**Comment by hanslovsky** [comment]
I do not know how pip/PyPI/conda/setuptools all play together and resolve the names. I know that the [distribution package name](https://packaging.python.org/glossary/) can be different from the import package name.

> If we publish to PyPI as javarun, but the module is still named jrun, does that cause a problem?

I don't think so, but I am also not an expert.

>  E.g.: what if someone wants to have both javarun and jrun installed at the same time? That would be problematic, no?  I guess only one of them would take precedence for import jrun statements?

I hope that this would be a clash at install time.

Maybe a python developer can handle the initial distribution to PyPI and conda.
